config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :commercial_units
  resources :complex_buildings
  resources :houses

  root 'home#index'

  post 'purchase', to: 'home#purchase', as: 'purchase'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commercial_unit.rb
class CommercialUnit < ApplicationRecord
  has_one_attached :image

  validates :owner, :owner_email, :address, :shops, :sqmt, :parking, :price, presence: true

end

app/models/complex_building.rb
class ComplexBuilding < ApplicationRecord
  has_one_attached :image

  validates :owner, :owner_email, :address, :units, :sqmt, :price, presence: true

end

app/models/house.rb
class House < ApplicationRecord
  has_one_attached :image

  validates :owner, :owner_email, :address, :rooms, :sqmt, :floors, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable#, :registerable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commercial_units_controller.rb
class CommercialUnitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commercial_unit, only: [:show, :edit, :update, :destroy]

  # GET /commercial_units
  # GET /commercial_units.json
  def index
    @commercial_units = CommercialUnit.all
  end

  # GET /commercial_units/1
  # GET /commercial_units/1.json
  def show
  end

  # GET /commercial_units/new
  def new
    @commercial_unit = CommercialUnit.new
  end

  # GET /commercial_units/1/edit
  def edit
  end

  # POST /commercial_units
  # POST /commercial_units.json
  def create
    @commercial_unit = CommercialUnit.new(commercial_unit_params)

    respond_to do |format|
      if @commercial_unit.save
        format.html { redirect_to @commercial_unit, notice: 'Commercial unit was successfully created.' }
        format.json { render :show, status: :created, location: @commercial_unit }
      else
        format.html { render :new }
        format.json { render json: @commercial_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commercial_units/1
  # PATCH/PUT /commercial_units/1.json
  def update
    respond_to do |format|
      if @commercial_unit.update(commercial_unit_params)
        format.html { redirect_to @commercial_unit, notice: 'Commercial unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @commercial_unit }
      else
        format.html { render :edit }
        format.json { render json: @commercial_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commercial_units/1
  # DELETE /commercial_units/1.json
  def destroy
    @commercial_unit.destroy
    respond_to do |format|
      format.html { redirect_to commercial_units_url, notice: 'Commercial unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commercial_unit
      @commercial_unit = CommercialUnit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def commercial_unit_params
      params.require(:commercial_unit).permit(:owner, :owner_email, :address, :shops, :sqmt, :parking, :price, :image)
    end
end

app/controllers/complex_buildings_controller.rb
class ComplexBuildingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_complex_building, only: [:show, :edit, :update, :destroy]

  # GET /complex_buildings
  # GET /complex_buildings.json
  def index
    @complex_buildings = ComplexBuilding.all
  end

  # GET /complex_buildings/1
  # GET /complex_buildings/1.json
  def show
  end

  # GET /complex_buildings/new
  def new
    @complex_building = ComplexBuilding.new
  end

  # GET /complex_buildings/1/edit
  def edit
  end

  # POST /complex_buildings
  # POST /complex_buildings.json
  def create
    @complex_building = ComplexBuilding.new(complex_building_params)

    respond_to do |format|
      if @complex_building.save
        format.html { redirect_to @complex_building, notice: 'Complex building was successfully created.' }
        format.json { render :show, status: :created, location: @complex_building }
      else
        format.html { render :new }
        format.json { render json: @complex_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complex_buildings/1
  # PATCH/PUT /complex_buildings/1.json
  def update
    respond_to do |format|
      if @complex_building.update(complex_building_params)
        format.html { redirect_to @complex_building, notice: 'Complex building was successfully updated.' }
        format.json { render :show, status: :ok, location: @complex_building }
      else
        format.html { render :edit }
        format.json { render json: @complex_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complex_buildings/1
  # DELETE /complex_buildings/1.json
  def destroy
    @complex_building.destroy
    respond_to do |format|
      format.html { redirect_to complex_buildings_url, notice: 'Complex building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complex_building
      @complex_building = ComplexBuilding.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def complex_building_params
      params.require(:complex_building).permit(:owner, :owner_email, :address, :units, :sqmt, :price, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @data = []
    @data << House.all.order('created_at desc')
    @data << CommercialUnit.all.order('created_at desc')
    @data << ComplexBuilding.all.order('created_at desc')
    @data = @data.compact.flatten
  end

  def purchase
    if params.key?('id') && params.key?('klass')
      owner_email = params["klass"].constantize.find_by(id: params["id"]).try(:owner_email)
      begin
	      LongTaskWorker.perform_async(owner_email)
	    rescue Exception => e
	    	puts e.message
	    end
      redirect_to root_url, notice: 'Operation Completed.'
    end
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def house_params
      params.require(:house).permit(:owner, :owner_email, :address, :rooms, :sqmt, :floors, :air_cond, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commercial_units_helper.rb
module CommercialUnitsHelper
end

app/helpers/complex_buildings_helper.rb
module ComplexBuildingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/commercial_units/_form.html.erb
<%= form_with(model: commercial_unit, local: true) do |form| %>
  <% if commercial_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(commercial_unit.errors.count, "error") %> prohibited this commercial_unit from being saved:</h2>

      <ul>
        <% commercial_unit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :owner %>
    <%= form.text_field :owner, class: 'form-control', required: true  %>
  </div>

  <div class="form-group">
    <%= form.label :owner_email %>
    <%= form.email_field :owner_email, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :shops %>
    <%= form.number_field :shops, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :sqmt %>
    <%= form.number_field :sqmt, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :parking %>
    <%= form.number_field :parking, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/commercial_units/edit.html.erb
<h1>Editing Commercial Unit</h1>

<%= render 'form', commercial_unit: @commercial_unit %>

<%= link_to 'Show', @commercial_unit, class: 'btn btn-success' %> |
<%= link_to 'Back', commercial_units_path, class: 'btn btn-primary' %>

app/views/commercial_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commercial Units</h1>

<table border="1" class="table">
  <thead>
    <tr>
      <th>Owner</th>
      <th>Owner Email</th>
      <th>Address</th>
      <th>Shops</th>
      <th>Sqmt</th>
      <th>Parking</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commercial_units.each do |commercial_unit| %>
      <tr>
        <td><%= commercial_unit.owner %></td>
        <td><%= commercial_unit.owner_email %></td>
        <td><%= commercial_unit.address %></td>
        <td><%= commercial_unit.shops %></td>
        <td><%= commercial_unit.sqmt %></td>
        <td><%= commercial_unit.parking %></td>
        <td><%= commercial_unit.price %></td>
        <td><%= image_tag(rails_blob_path(commercial_unit.image), width: 150 ) if commercial_unit.image.attached? %></td>
        <td><%= link_to 'Show', commercial_unit, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Edit', edit_commercial_unit_path(commercial_unit), class: 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Destroy', commercial_unit, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commercial Unit', new_commercial_unit_path, class: 'btn btn-primary' %>

app/views/commercial_units/new.html.erb
<h1>New Commercial Unit</h1>

<%= render 'form', commercial_unit: @commercial_unit %>

<%= link_to 'Back', commercial_units_path, class: 'btn btn-primary' %>

app/views/commercial_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @commercial_unit.owner %>
</p>

<p>
  <strong>Owner Email:</strong>
  <%= @commercial_unit.owner_email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @commercial_unit.address %>
</p>

<p>
  <strong>Shops:</strong>
  <%= @commercial_unit.shops %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @commercial_unit.sqmt %>
</p>

<p>
  <strong>Parking:</strong>
  <%= @commercial_unit.parking %>
</p>

<p>
  <strong>Price:</strong>
  <%= @commercial_unit.price %>
</p>

<p>
  <%= image_tag(rails_blob_path(@commercial_unit.image), width: 300 ) if @commercial_unit.image.attached? %>
</p>

<%= link_to 'Edit', edit_commercial_unit_path(@commercial_unit), class: 'btn btn-success' %> |
<%= link_to 'Back', commercial_units_path, class: 'btn btn-primary' %>

app/views/complex_buildings/_form.html.erb
<%= form_with(model: complex_building, local: true) do |form| %>
  <% if complex_building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complex_building.errors.count, "error") %> prohibited this complex_building from being saved:</h2>

      <ul>
        <% complex_building.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :owner %>
    <%= form.text_field :owner, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :owner_email %>
    <%= form.email_field :owner_email, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :units %>
    <%= form.number_field :units, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :sqmt %>
    <%= form.number_field :sqmt, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/complex_buildings/edit.html.erb
<h1>Editing Complex Building</h1>

<%= render 'form', complex_building: @complex_building %>

<%= link_to 'Show', @complex_building, class: 'btn btn-success' %> |
<%= link_to 'Back', complex_buildings_path, class: 'btn btn-primary' %>

app/views/complex_buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complex Buildings</h1>

<table border="1" class="table">
  <thead>
    <tr>
      <th>Owner</th>
      <th>Owner Email</th>
      <th>Address</th>
      <th>Units</th>
      <th>Sqmt</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complex_buildings.each do |complex_building| %>
      <tr>
        <td><%= complex_building.owner %></td>
        <td><%= complex_building.owner_email %></td>
        <td><%= complex_building.address %></td>
        <td><%= complex_building.units %></td>
        <td><%= complex_building.sqmt %></td>
        <td><%= complex_building.price %></td>
        <td><%= image_tag(rails_blob_path(complex_building.image), width: 150 ) if complex_building.image.attached? %></td>
        <td><%= link_to 'Show', complex_building, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Edit', edit_complex_building_path(complex_building), class: 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Destroy', complex_building, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complex Building', new_complex_building_path, class: 'btn btn-primary' %>

app/views/complex_buildings/new.html.erb
<h1>New Complex Building</h1>

<%= render 'form', complex_building: @complex_building %>

<%= link_to 'Back', complex_buildings_path, class: 'btn btn-primary' %>

app/views/complex_buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @complex_building.owner %>
</p>

<p>
  <strong>Owner Email:</strong>
  <%= @complex_building.owner_email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @complex_building.address %>
</p>

<p>
  <strong>Units:</strong>
  <%= @complex_building.units %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @complex_building.sqmt %>
</p>

<p>
  <strong>Price:</strong>
  <%= @complex_building.price %>
</p>

<p>
  <%= image_tag(rails_blob_path(@complex_building.image), width: 300 ) if @complex_building.image.attached? %>
</p>

<%= link_to 'Edit', edit_complex_building_path(@complex_building), class: 'btn btn-success' %> |
<%= link_to 'Back', complex_buildings_path, class: 'btn btn-primary' %>

app/views/home/index.html.erb
<% @data.each do |obj| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-block">
        <%= image_tag(rails_blob_path(obj.image), class: 'image' ) if obj.image.attached? %>
        <div class="middle">
          <div class="text">
            <div class="card-subtitle"><%= obj.class %></div>
            <div class="card-subtitle"><%= "Owner: #{obj.owner}" %></div>
            <div class="card-subtitle"><%= "Address: #{obj.address}" %></div>
            <div class="card-subtitle"><%= "Sqmt: #{obj.sqmt}" %></div>

            <% if obj.class == House %>
              <div class="card-subtitle"><%= "Rooms: #{obj.rooms}" %></div>
              <div class="card-subtitle"><%= "Floors: #{obj.floors}" %></div>
              <div class="card-subtitle"><%= "AC: #{obj.air_cond}" %></div>
            <% elsif obj.class == ComplexBuilding %>
              <div class="card-subtitle"><%= "Units: #{obj.units}" %></div>
            <% elsif obj.class == CommercialUnit %>
              <div class="card-subtitle"><%= "Shops: #{obj.shops}" %></div>
              <div class="card-subtitle"><%= "Parking: #{obj.parking}" %></div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <div class="price"><%= "Price: $#{obj.price}" %></div>
        <%= button_to "Buy", purchase_path(klass: obj.class.to_s, id: obj.id), class: "buy_btn btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<style type="text/css">
  .card {
    position: relative;
    display: flex;
    flex-direction: column;
    background-color: #fff;
    border: 1px solid rgba(0, 0, 0, 0.125);
    border-radius: 0.25rem;
    margin-bottom: 20px;
  }

  .card-block {
    flex: 1 1 auto;
    padding: 1.25rem;
    position: relative;
    width: 50%;
  }

  .price{
    padding: 0 1.25rem;
    font-size: 1.5rem;
    font-weight: bold;
    float: left;
    margin-top: 5px;
  }

  .buy_btn{
    float: right;
    margin-right: 8px;
  }

  .image {
    opacity: 1;
    display: block;
    /*width: 100%;*/
    height: auto;
    transition: .5s ease;
    backface-visibility: hidden;
    width: 330px;
    height:200px;
  }

  .middle {
    transition: .5s ease;
    opacity: 0;
    position: absolute;
    top: 50%;
    left: 100%;
    transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    text-align: center;
    width: 100%;
  }

  .card-block:hover .image {
    opacity: 0.3;
  }

  .card-block:hover .middle {
    opacity: 1;
  }

  .text {
    background-color: #4CAF50;
    color: white;
    font-size: 16px;
    padding: 10px;
  }

  .card-footer{
    display: inline-block;
    margin-bottom: 8px;
    /*display: flex;*/
    /*justify-content: space-between;*/
  }

</style>

app/views/houses/_form.html.erb
<%= form_with(model: house, local: true) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :owner %>
    <%= form.text_field :owner, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :owner_email %>
    <%= form.email_field :owner_email, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :rooms %>
    <%= form.number_field :rooms, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :sqmt %>
    <%= form.number_field :sqmt, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :floors %>
    <%= form.number_field :floors, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :air_cond %>
    <%= form.select :air_cond, [ true, false ], {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house, class: 'btn btn-success' %> |
<%= link_to 'Back', houses_path, class: 'btn btn-primary' %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table border="1" class="table">
  <thead>
    <tr>
      <th>Owner</th>
      <th>Owner Email</th>
      <th>Address</th>
      <th>Rooms</th>
      <th>Sqmt</th>
      <th>Floors</th>
      <th>Air cond</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.owner %></td>
        <td><%= house.owner_email %></td>
        <td><%= house.address %></td>
        <td><%= house.rooms %></td>
        <td><%= house.sqmt %></td>
        <td><%= house.floors %></td>
        <td><%= house.air_cond %></td>
        <td><%= house.price %></td>
        <td><%= image_tag(rails_blob_path(house.image), width: 150 ) if house.image.attached? %></td>
        <td><%= link_to 'Show', house, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Edit', edit_house_path(house), class: 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path, class: 'btn btn-primary' %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path, class: 'btn btn-primary' %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @house.owner %>
</p>

<p>
  <strong>Owner Email:</strong>
  <%= @house.owner_email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @house.address %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @house.rooms %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @house.sqmt %>
</p>

<p>
  <strong>Floors:</strong>
  <%= @house.floors %>
</p>

<p>
  <strong>Air cond:</strong>
  <%= @house.air_cond %>
</p>

<p>
  <strong>Price:</strong>
  <%= @house.price %>
</p>

<p>
  <%= image_tag(rails_blob_path(@house.image), width: 300 ) if @house.image.attached? %>
</p>

<%= link_to 'Edit', edit_house_path(@house), class: 'btn btn-success' %> |
<%= link_to 'Back', houses_path, class: 'btn btn-primary' %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Brand</a> -->
    </div>

    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Houses', houses_path %></li>
          <li><%= link_to 'Complex Building', complex_buildings_path %></li>
          <li><%= link_to 'Commericial Unit', commercial_units_path %></li>
        </ul>
        <p class="navbar-text navbar-right">
          Signed in as <a href="#" class="navbar-link"><%= current_user.email %></a>
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
        </p>
      </div>

    <% else %>
      <div class="collapse navbar-collapse">
        <p class="navbar-text navbar-right">
          <%#= link_to 'Register', new_user_registration_path %> <%= link_to 'Login', new_user_session_path %>
        </p>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealEstate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if notice %><p class="alert alert-success"><%= notice %></p><% end %>
    <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>

  <style type="text/css">
    a{
      color: white !important;
    }
  </style>

  <script type="text/javascript">
    setTimeout(function() { $('.alert').fadeOut('fast'); }, 3000);
  </script>
</html>